### ISSUE TITLE
location/proximity API call

### ISSUE THREAD

**Issue by love-lena** [svm-ucsc/smart-vending-API#42]
takes in a coordinate (probably lat-long) and maybe a range (can set sensible default of 1 mile for now)
can also take in a machine_id to find nearby machines. lat-long is the only essential one

returns all machine_ids within that range

consider adding "hardcoded" proximities of nearby machines on each machine

**Comment by cngcruz** [comment]
For now, an unsorted  list of machine_ids within a range is fine to get the location feature up and running.
A later thing (more of a UX thing), we would want a sorted list of machine_ids from closest to farthest.

**Comment by love-lena** [comment]
Searching for nearby items works, but we don't have a search for nearby machines yet. So this issue is half resolved
